openapi: 3.0.3
info:
  title: Usuarios
  description: |-
    API de usuários da aplicação byTongue criado a partir das definições de "design first" ou API First, cujo se baseia na criação da documentação antes do desenvolvimento em si da ferramenta.
    
  termsOfService: http://bytongue.com/terms/
  contact:
    email: contato@bytongue.com
  version: 0.1.1
servers:
  - url: https://bytongue.com/
tags:
  - name: users
    description: Operações acerca dos usuários de forma genérica
  - name: sessions
    description: Operações de autenticação de usuário
  - name: chats
    description: Operações acerca dos endereços do usuário
    externalDocs:
      description: Ler documentação
      url: https://github.com/Kaindall/ByTongue_DSM
paths:
  /users:
    post:
      tags:
        - users
      summary: Criar usuário
      description: Cria um usuário
      operationId: createUser
      requestBody:
        description: Dados do usuário
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: Usuário registrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 10
  /users/login:
    post:
      tags:
        - sessions
      summary: Inicializar sessão do usuário
      description: ''
      operationId: loginUser
      requestBody:
        description: Valores a serem atualizados
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Usuário identificado com sucesso!
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Usuário ou senha informados são inválidos
  /users/logout:
    get:
      tags:
        - sessions
      summary: Finalizar a sessão do usuário atual
      description: ''
      operationId: logoutUser
      parameters: []
      responses:
        '200':
          description: Usuário deslogado com sucesso
        '400':
          description: Requisição inválida
  /users/{id_user}:
    get:
      tags:
        - users
      summary: Buscar e retornar o usuário
      description: ''
      operationId: getUserById
      parameters:
        - name: id_user
          in: path
          description: Id do usuário a ser buscado
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operação bem-sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'        
        '404':
          description: Usuário não encontrado
    put:
      tags:
        - users
      summary: Atualizar o usuário
      description: ""
      operationId: updateUserById
      parameters:
        - name: id_user
          in: path
          description: Id do usuário a ser atualizado
          required: true
          schema:
            type: string
      requestBody:
        description: Valores a serem atualizados
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '204':
          description: Operação bem-sucedida ou nenhum dado alterado
        '400':
          description: Requisição inválida
        '404':
          description: Usuário não encontrado
    delete:
      tags:
        - users
      summary: Excluir o usuário
      description: Só pode ser utilizado através de um usuário autenticado
      operationId: deleteUserById
      parameters:
        - name: id_user
          in: path
          description: Id do usuário a ser apagado
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Operação bem-sucedida
        '400':
          description: Requisição inválida
        '404':
          description: Usuário não encontrado
  /users/{id_user}/chats:
    get:
      tags:
        - chats
      summary: Buscar e retornar conversas atreladas ao usuário
      description: ''
      operationId: findUserAdresses
      parameters:
        - name: id_user
          in: path
          description: Id do usuário cujo as conversas serão buscados
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operação bem-sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatsResponse'
        '404':
          description: Nenhuma conversa encontrada
components:
  schemas:
    CreateUserRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
          format: password
        birthday:
          type: string
          format: date
      example:
        name: "Generic John"
        email: "generic@email.com"
        password: "123456"
        birthday: "1980/09/22"
    UpdateUserRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
          format: password
        birthday:
          type: string
          format: date
      example:
        name: "Generic Updated John"
    UserLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: "genericUser"
        password: "123456"
    UserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: "Generic John"
        email:
          type: string
          example: "generic@email.com"
        birthday:
          type: string
          format: date
          example: "1980/09/15"
    ChatResponse:
      type: object
      properties:
        chat_id: 
          type: string
        title:
          type: string
        created_date:
          type: string
          format: date
        update_date:
          type: string
          format: date
      example:
        chat_id: "1565645-AHJSBIAS-21132"
        title: "Se você espera o inesperado, ele se torna esperado?"
        created_date: "22/05/2024"
        update_date: "25/05/2024"
    ChatsResponse:
      type: array
      items:
        $ref: '#/components/schemas/ChatResponse'
      
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header